baseURL = "https://www.beigang.org/"
languageCode = "en-us"
title = "Fabian Beigang"
theme = "avicenna"

[params]
  subtitle= "Data Scientist and Philosopher"
  cv_name= "https://drive.google.com/file/d/1hirrdWShto3PDTODuCuEp4BNDqRkDbJu/view?usp=sharing"


[[params.affilation]]
  name = "London School of Economics and Political Science"
  position = "Data Scientist and Philosopher"
  contact = "f.beigang@lse.ac.uk"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/beigang/"
  
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/fabianbeigang"


[[params.introduction.paragraph]]
  text="""I am a Data Scientist at the Northumbria Healthcare NHS Foundation Trust. Previously, I was a PhD student at the London School of Economics and Political Science, working
  on bias and fairness in machine learning models.  """
  
[[params.publications]]
  	[[params.publications.paper]]
		name = "On the Advantages of Distinguishing Between Predictive and Allocative Fairness in Algorithmic Decision-Making"
		dest  = "*Minds and Machines*, 2022"
		link = "https://link.springer.com/article/10.1007/s11023-022-09615-9"
	[[params.publications.paper]]
		name = "Counterfactual Fairness, Equalized Odds, and Calibration: Yet Another Impossibility Theorem"
		dest  = "(under review)"
		link = "https://drive.google.com/file/d/1Z-crA8qF4g16n0y20_ezju6AlORFLeCq/view?usp=sharing"

		
