baseURL = "https://www.beigang.org/"
languageCode = "en-us"
title = "Fabian Beigang"
theme = "avicenna"

[params]
  subtitle= "Data Scientist and Researcher"
  cv_name= "https://drive.google.com/file/d/1hirrdWShto3PDTODuCuEp4BNDqRkDbJu/view?usp=sharing"


[[params.affilation]]
  name = ""
  position = "Senior Data Scientist (NHS) and Researcher (LSE)"
  contact = "fabian.beigang@northumbria-healthcare.nhs.uk | f.beigang@lse.ac.uk"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/beigang/"
  
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/fabianbeigang"


[[params.introduction.paragraph]]
  text="""I am a Senior Data Scientist at the Northumbria Healthcare NHS Foundation Trust and a Visiting Fellow (PhD Graduate) at the London School of Economics. Previously, I was a PhD student at the London School of Economics and Political Science at the Department of Philosophy, Logic, and Scientific Method, working
  on bias and fairness in machine learning models.  """
  
[[params.publications]]
  	[[params.publications.paper]]
		name = "Yet Another Impossibility Theorem in Algorithmic Fairness"
		dest  = "*Minds and Machines*, 2023"
		link = "https://link.springer.com/article/10.1007/s11023-023-09645-x"
	[[params.publications.paper]]
		name = "Reconciling Algorithmic Fairness Criteria"
		dest  = "*Philosophy and Public Affairs*, 2023 (open access)"
		link = "https://onlinelibrary.wiley.com/journal/10884963"
	[[params.publications.paper]]
		name = "On the Advantages of Distinguishing Between Predictive and Allocative Fairness in Algorithmic Decision-Making"
		dest  = "*Minds and Machines*, 2022 (open access)"
		link = "https://link.springer.com/article/10.1007/s11023-022-09615-9"

		
