baseURL = "https://www.beigang.org/"
languageCode = "en-us"
title = "Fabian Beigang"
theme = "avicenna"

[params]
  subtitle= "PhD Student"
  cv_name= "https://drive.google.com/file/d/1X_-ZZXHi2Bb_KJkTa-UCBJNFUw6jsbYR/view?usp=sharing"


[[params.affilation]]
  name = "London School of Economics and Political Science"
  position = "PhD Student"
  contact = "f.beigang@lse.ac.uk"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/fabianlse/"


[[params.introduction.paragraph]]
  text=""" My PhD project addresses the question which formal constraints need
  to be imposed on algorithmic decision systems in order to ensure that they don't
  produce outcomes that are in conflict with relevant ethical norms. My aim is to draw
  on existing literature on discrimination and equality of opportunity to analyze how algorithmic decision-making
  procedures and their outcomes can potentially be morally objectionable and, consequently, which ethical norms they might violate. Making use of the mathematical formalism of causal modelling, I then intend to
 translate the resulting norms into formal language, so that they are applicable to algorithmic systems. """
[[params.introduction.paragraph]]
  text=""" Other philosophical projects I pursue are in formal and social epistemology, and causal modelling. Besides that, I occasionally venture into the realms of statistics and machine learning.
  """



